from datetime import datetime

from scrapy import Selector

scrapingbee_api_key = "N5S4WPYMW534HUU079AERKCRPDUNJTYIH7OV09TPEZEQKOSM21JQO6AY6UF08VLLEO5QXQNICNLQKXD5"
scrapingbee_proxy_url = ("https://app.scrapingbee.com/api/v1/?api_key=" + scrapingbee_api_key +
                         "&url={}&forward_headers=true&country_code=us"
                         # "&premium_proxy=true"
                         # "&stealth_proxy=true"
                         )

scrapingbee_premium_proxy_url = ("https://app.scrapingbee.com/api/v1/?api_key=" + scrapingbee_api_key +
                                 "&url={}&forward_headers=true&country_code=us"
                                 "&premium_proxy=true"
                                 )

scrapingbee_stealth_proxy_url = ("https://app.scrapingbee.com/api/v1/?api_key=" + scrapingbee_api_key +
                                 "&url={}&forward_headers=true&country_code=us"
                                 "&stealth_proxy=true"
                                 )

today_date = datetime.now().strftime('%d%b%Y')

handle_httpstatus_list = [
    400, 401, 402, 403, 404, 405, 406, 407, 409,
    500, 501, 502, 503, 504, 505, 506, 507, 509,
]

req_meta = {
    'handle_httpstatus_list': handle_httpstatus_list,
    # "proxy": f"http://{scraping_bee_api_key}:huwaiguest@gmail.com:8886",
    # "proxy": f"http://scrapingbee:{scrapingbee_api_key}@proxy-server.scrapingbee.com:8886"
}

scrapingbee_params = {
    'api_key': scrapingbee_api_key,
    'url': 'http://httpbin.org/anything?json',
    # 'premium_proxy': 'true',
    # 'stealth_proxy': 'true',
    'country_code': 'us'
}

csv_headers = [
    'date', 'product_id', 'product_name', 'upc', 'vendor', 'sku', 'price', 'in_stock',
    'has_variants', 'product_url', 'product_cart_id',
    #  'main_image_url', 'secondary_image_urls', 'quantity', 'description',

    # More information fields
    # 'fluorescent_bulb_wattage', 'maximum_system_volume', 'control_type', 'aquarium_type',
    # 'compatible_with_controllers', 'included_mounting', 'wattage', 'optional_mounts',
    # 'ml_per_minute', 'short_name_for_grouped_product', 'media_capacity', 'filter_dimensions', 'main_ingredient',
    # 'skimmer_body_types', 'bulb_color/temperature', 'system_size', 'variable_speed', 'power_cord_length',
    # 'pvc_connection_type', 'additive_type', 'max._light_coverage_(width)', 'max._light_coverage_(length)',
    # 'adhesive_type', 'out_of_stock_message', 'micron_rating', 'manuals', 'recommended_tank_size',
    # 'tubing_inside_diameter', 'aquarium_size', 'reactor_placement', 'lighting_type', 'system_type', 'color',
    # 'max_head_height', 'duty_rating', 'warranty', 'alarms', 'number_of_leds', 'dimensions', 'weight'
]

user_agents = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/79.0.3945.117 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/79.0.3945.117 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36',
    'Mozilla/5.0 (Linux; Android 8.0.0;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 '
    'Mobile Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) '
    'CriOS/79.0.3945.73 Mobile/15E148 Safari/605.1',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/72.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/72.0',
    'Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/72.0',
    'Mozilla/5.0 (Android 8.0.0; Mobile; rv:61.0) Gecko/61.0 Firefox/68.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
    'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/21.0 '
    'Mobile/16B92 Safari/605.1.15',
    'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 YaBrowser/19.7.3.172 '
    'Yowser/2.5 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/79.0.3945.117 YaBrowser/19.6.0.1583 Yowser/2.5 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) '
    'Version/12.0 YaBrowser/19.12.2.263 Mobile/15A432 Safari/602.1',
    'Mozilla/5.0 (Linux; Android 8.0.0;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 '
    'YaBrowser/19.10.4.187 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 '
    'Safari/537.36 Vivaldi/2.10',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko)',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64)Chrome/79.0.3945.117 Safari/537.36 OPR/66.0.3515.27',
    'Mozilla/5.0 (Macintosh;Chrome/79.0.3945.117 Safari/537.36 OPR/66.0.3515.27',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
    'Mozilla/5.0 (Linux; Android 9; AppleWebKit/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64)Chrome/79.0.3945.117 Safari/537.36 Edg/44.18362.449.0',
    'Mozilla/5.0 (Windows Mobile 10; Android 8.0.0; Microsoft; Lumia 950XL)',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One)',
    'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)',
    'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2)',
    'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15',
    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15',
    'Mozilla/5.0 (iPod Touch; CPU iPhone OS 12_2 like Mac OS X)',
]

# source_html = ""
# response = Selector(text=source_html)
# category_urls = response.css('.submenu li.category-item a::attr(href)').getall()[::-1]

category_urls = [
    "https://www.bulkreefsupply.com/freshwater/aquariums.html",
    "https://www.bulkreefsupply.com/freshwater/maintenance.html",
    "https://www.bulkreefsupply.com/freshwater/substrate-decor.html",
    "https://www.bulkreefsupply.com/freshwater/filtration.html",
    "https://www.bulkreefsupply.com/freshwater/additives.html",
    "https://www.bulkreefsupply.com/freshwater/fish-food-feeding-tools.html",
    "https://www.bulkreefsupply.com/freshwater/temperature-control.html",
    "https://www.bulkreefsupply.com/freshwater/lighting.html",
    "https://www.bulkreefsupply.com/live-goods/coralline-algae.html",
    "https://www.bulkreefsupply.com/live-goods/coralline-algae.html",
    "https://www.bulkreefsupply.com/live-goods/refugium-starter-kits.html",
    "https://www.bulkreefsupply.com/live-goods/refugium-starter-kits.html",
    "https://www.bulkreefsupply.com/live-goods/pods-phyto.html",
    "https://www.bulkreefsupply.com/live-goods/pods-phyto.html",
    "https://www.bulkreefsupply.com/live-goods/macro-algae.html",
    "https://www.bulkreefsupply.com/live-goods/macro-algae.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/coral-dip.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/coral-dip.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/super-glue-epoxies.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/super-glue-epoxies.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/racks-egg-crate-frag-tanks.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/racks-egg-crate-frag-tanks.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/fragging-tools.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/fragging-tools.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/frag-plugs-disks.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/frag-plugs-disks.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights/oceans-wonders.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights/coral-rx.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights/bulk-reef-supply.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights.html",
    "https://www.bulkreefsupply.com/saltwater-aquarium-fragging-supplies/wholesale-fragging-highlights.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/aquascaping.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/aquascaping.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/cycling-curing.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/cycling-curing.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wood.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wood.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/aquarium-live-sand.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/aquarium-live-sand.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/dry-live-rock.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/dry-live-rock.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wholesale-highlights/cycling-and-aquascaping.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wholesale-highlights/live-sand.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wholesale-highlights/dry-live-rock.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/bulk-dry-live-rock-live-sand/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-feeding-tools.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-feeding-tools.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/automatic-fish-feeders.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/automatic-fish-feeders.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/live-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/live-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/frozen-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/frozen-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/v2o-aquarium-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/two-little-fishies.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/tropic-marin.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/seachem.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/rod-s-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/reef-nutrition.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/reef-chili-coral-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/polyplab.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/nyos-coral-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/korallen-zucht-coral-nutrition.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/fauna-marin-coral-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/easy-reefs.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/bulk-reef-supply.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/aquaforest.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods/specialty.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/coral-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/v2o-aquarium-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/two-little-fishies-fish-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/sustainable-aquatics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/rod-s-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/reef-nutrition.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/piscine-energetics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/nyos-fish-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/neptune-systems.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/hikari.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/fauna-marin-fish-food.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/easy-reefs.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/bulk-reef-supply.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/dr-bassleer.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods/specialty.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/fish-foods.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/doctor-eco-systems.html",
    "https://www.bulkreefsupply.com/catalog/category/view/s/hw-wiegandt/id/622/",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/reef-nutrition.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/cobalt-aquatics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/hikari.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights/reef-chili.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights.html",
    "https://www.bulkreefsupply.com/fish-coral-foods/wholesale-food-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/thermometers-controllers.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/thermometers-controllers.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-fans.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-fans.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-chillers.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-chillers.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-heaters.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/aquarium-heaters.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/wholesale-heater-and-chiller-highlights/eheim.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/wholesale-heater-and-chiller-highlights/bulk-reef-supply.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/wholesale-heater-and-chiller-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-heaters-chillers/wholesale-heater-and-chiller-highlights.html",
    "https://www.bulkreefsupply.com/auto-top-off/float-switches-solenoids.html",
    "https://www.bulkreefsupply.com/auto-top-off/float-switches-solenoids.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/auto-top-off-reservoirs.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/auto-top-off-reservoirs.html",
    "https://www.bulkreefsupply.com/auto-top-off/auto-top-off-pumps.html",
    "https://www.bulkreefsupply.com/auto-top-off/auto-top-off-pumps.html",
    "https://www.bulkreefsupply.com/auto-top-off/auto-top-off-systems.html",
    "https://www.bulkreefsupply.com/auto-top-off/auto-top-off-systems.html",
    "https://www.bulkreefsupply.com/auto-top-off/wholesale-ato-highlights/trigger-systems.html",
    "https://www.bulkreefsupply.com/auto-top-off/wholesale-ato-highlights/autoaqua.html",
    "https://www.bulkreefsupply.com/auto-top-off/wholesale-ato-highlights/tunze.html",
    "https://www.bulkreefsupply.com/auto-top-off/wholesale-ato-highlights.html",
    "https://www.bulkreefsupply.com/auto-top-off/wholesale-ato-highlights.html",
    "https://www.bulkreefsupply.com/filter-media/media-bags-reactors.html",
    "https://www.bulkreefsupply.com/filter-media/media-bags-reactors.html",
    "https://www.bulkreefsupply.com/filter-media/specialty-media.html",
    "https://www.bulkreefsupply.com/filter-media/specialty-media.html",
    "https://www.bulkreefsupply.com/filter-media/carbon-dioxide-media.html",
    "https://www.bulkreefsupply.com/filter-media/carbon-dioxide-media.html",
    "https://www.bulkreefsupply.com/filter-media/calcium-reactor-media.html",
    "https://www.bulkreefsupply.com/filter-media/calcium-reactor-media.html",
    "https://www.bulkreefsupply.com/filter-media/biological-filtration-media.html",
    "https://www.bulkreefsupply.com/filter-media/biological-filtration-media.html",
    "https://www.bulkreefsupply.com/filter-media/phosphate-removal-media-gfo.html",
    "https://www.bulkreefsupply.com/filter-media/phosphate-removal-media-gfo.html",
    "https://www.bulkreefsupply.com/filter-media/carbon.html",
    "https://www.bulkreefsupply.com/filter-media/carbon.html",
    "https://www.bulkreefsupply.com/filter-media/biopellets.html",
    "https://www.bulkreefsupply.com/filter-media/biopellets.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights/marine-pure.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights/boyd-enterprises.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights/brs-filter-media.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/filter-media/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/protein-skimmers/skimmer-accessories.html",
    "https://www.bulkreefsupply.com/protein-skimmers/skimmer-accessories.html",
    "https://www.bulkreefsupply.com/protein-skimmers/uv-sterilizers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/uv-sterilizers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/ozone-equipment/air-dryers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/ozone-equipment/kynar-fittings.html",
    "https://www.bulkreefsupply.com/protein-skimmers/ozone-equipment/ozone-generators.html",
    "https://www.bulkreefsupply.com/protein-skimmers/ozone-equipment.html",
    "https://www.bulkreefsupply.com/protein-skimmers/ozone-equipment.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads/power-hob-filters.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads/rollermat-fleece.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads/filter-pads.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads/filter-socks-holders.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads.html",
    "https://www.bulkreefsupply.com/protein-skimmers/fleece-rollers-power-filters-socks-and-pads.html",
    "https://www.bulkreefsupply.com/protein-skimmers/hang-on-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/hang-on-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/recirculating-and-external-protein-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/recirculating-and-external-protein-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/adaptive-reef.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/ultra-reef.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/tunze.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/eshopps-internal-protein-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/nyos.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/maxspect.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/auqa-gadget-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/icecap.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/hydor.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/bubble-magus.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/aquamaxx.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/internal-reef-octopus.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/red-sea.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers/royal-exclusiv.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/internal-protein-skimmers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/co2-scrubbers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/zeovit-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/kalkwasser-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/calcium-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/carbon-gfo-media-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/biopellet-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors/algae-reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/reactors.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights/pentair-formerly-emperor-aquatics.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights/lifegard-aquatics.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights/clear-water-scrubbers.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights/bulk-reef-supply.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/protein-skimmers/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/general-tank-maintenance.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/general-tank-maintenance.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/water-change-systems.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/water-change-systems.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/tank-safety.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/tank-safety.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/nets-traps-tongs-acclimators.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/nets-traps-tongs-acclimators.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/medications.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/medications.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/aquarium-glass-and-acrylic-cleaners.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/aquarium-glass-and-acrylic-cleaners.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/filter-socks.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/filter-socks.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/salt-mix.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/salt-mix.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/python.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/lifegard.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/hw-wiegandt.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/hikari.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/brightwell-aquatics.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/flipper.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/algae-free.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights/brs-filter-socks.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/tank-maintenance-salt-mix/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/auto-water-change-systems.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/auto-water-change-systems.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/underwater-cameras.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/underwater-cameras.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/timers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/timers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/probes-accessories.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/probes-accessories.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hanna-checker/hanna-accessories.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hanna-checker/fresh-water-hanna-checkers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hanna-checker/saltwater-hanna-checker.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hanna-checker.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hanna-checker.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hydrometers-refractometers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/hydrometers-refractometers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/focustronic.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/xp-aqua.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/tunze.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/pinpoint-aquarium-monitors-controllers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/milwaukee-aquarium-monitors-controllers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/kill-a-watt.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/autoaqua.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/apogee.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/adaptive-reef.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/ghl.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/seneye.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/coralvue-hydros.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors/neptune-systems-aquarium-controllers.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/controllers-monitors.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/minor-trace-element-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/ph-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/ammonia-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/nitrate-nitrite-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/phosphate-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/magnesium-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/calcium-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/alkalinity-dkh-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing/multi-parameter-test-kits.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/testing.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights/seneye.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights/lamotte-test-strips.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights/brs-refractometers-probes.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights/red-sea.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights/salifert.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-monitors-controllers/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/canisters-brackets-and-clips.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/canisters-brackets-and-clips.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing/source-water-connections.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing/valves.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing/tubing.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing/fittings.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-fittings-valves-plumbing.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-accessories/upgrade-kits.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-accessories/monitors-meters-controllers.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-accessories/booster-pumps-accessories.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-accessories.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-accessories.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/reverse-osmosis-membranes.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/di-resin.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/sediment-filters.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/carbon-blocks-sediment-filters.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/7-stage-filter-kits.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/6-stage-filter-kits.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/5-stage-filter-kits.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters/4-stage-filter-kits.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-filters.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems/drinking-water-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems/7-stage-ro-di-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems/6-stage-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems/5-stage-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems/4-stage-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/reverse-osmosis-systems.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di/mur-lok.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di/aquatech.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di/hm-digital.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di/brs-ro-di-filters.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di/ro-di-units.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di.html",
    "https://www.bulkreefsupply.com/bulk-reverse-osmosis-filters-systems/wholesale-ro-di.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/freshwater-additives.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/freshwater-additives.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dosing/accessories.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dosing/reservoirs.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dosing/dosing-pumps.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dosing.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dosing.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/two-little-fishes-aquarium-additives.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/two-little-fishes-aquarium-additives.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/tropic-marin.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/tropic-marin.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/triton/seawater-treatments.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/triton/seawater-supplements.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/triton/triton-method.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/triton.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/triton.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/seachem.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/seachem.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/polyplab.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/polyplab.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/nyos.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/esv.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/esv.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dr-tims-aquatics.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/dr-tims-aquatics.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/hw-wiegandt/trace-elements.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/hw-wiegandt/problem-solvers.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/hw-wiegandt.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/hw-wiegandt.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea/biofiltration-nutrtient-control.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea/trace-elements.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea/coral-nutrition.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea/cal-alk.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/red-sea.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell/biofiltration-nutrtient-control.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell/trace-elements.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell/coral-nutrition.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell/ca-alk.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brightwell.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/ati.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/ati.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest/biofiltration-nutrient-control.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest/coral-nutrition.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest/trace-elements.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest/calcium-alkalinity-magnesium.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/aquaforest.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht/problem-solvers.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht/coral-nutrition-korallen-zucht.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht/kz-color-enhancers.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht/kz-zeovit-system.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/korallen-zucht.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs-aquarium-additives/magnesium.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs-aquarium-additives/alkalinity.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs-aquarium-additives/calcium.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs-aquarium-additives/kalkwasser.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/brs.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/brightwell.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/dr-tim-s-30.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/hw-wiegandt.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/red-sea.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/korallen-zucht.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights/brs.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/calcium-alkalinity-trace-elements/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/air-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/air-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/overflows/external-hob-overflows.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/overflows/internal-overflows.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/overflows.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/overflows.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/saltwater-aquarium-dosing-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/saltwater-aquarium-dosing-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/valves.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/uniseals.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/pipe-tubing.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/schedule-40-fittings.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/schedule-80-fittings.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/barbed-plumbing-fittings.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/quick-connect-fittings.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/loc-line.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/glass-drill-bits.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing/bulkheads.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/plumbing.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/sicce.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/reef-octopus.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/reeflo.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/neptune-systems.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/iwaki-external-aquarium-pump.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/ecotech.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps/abyzz.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/external-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/reefbreeders.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/sicce-submersible-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/royal-exclusiv.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/reef-octopus.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/newa.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/neptune-systems.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/maxspect.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/lifegard.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/innovative-marine.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/eheim.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/ecotech.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/current-usa.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps/abyzz.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/submersible-aquarium-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/tunze.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/sicce-powerhead-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/reef-octopus.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/reef-breeders.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/red-sea.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/newa.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/neptune-systems.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/maxspect-gyre.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/maxijet-powerhead-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/jbj.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/innovative-marine.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/icecap.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/vortech.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/current-usa.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps/aqua-illumination.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/aquarium-powerhead-pumps.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/cepex.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/loc-line.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/bulkheads.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/bubble-magus.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/lifegard.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/eheim.html",
    "https://www.bulkreefsupply.com/catalog/category/view/s/cobalt-aquatics/id/637/",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/sicce.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights/bulk-reef-supply-dosers.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights.html",
    "https://www.bulkreefsupply.com/pumps-plumbing/wholesale-pump-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/timers.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/timers.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/par-meters-timers.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/par-meters-timers.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/refugium-led.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/refugium-led.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/metal-halide-aquarium-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/metal-halide-aquarium-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting/retrofit.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting/fixtures.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting/bulbs.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting/ballasts.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/t5-fluorescent-aquarium-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/tunze.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/reef-brite.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/reef-breeders-leds.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/red-sea.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/orphek.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/maxspect-led-aquarium-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/ghl.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/current-usa.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/aquatic-life.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/aquamaxx.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/kessil-led.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/aqua-illumination.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/neptune-systems.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting/ecotech-radion.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/aquarium-led-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/hybrid-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/hybrid-lighting.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/wholesale-lighting-highlights/seneye.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/wholesale-lighting-highlights/aqua-illumination.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/wholesale-lighting-highlights/kessil.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/wholesale-lighting-highlights.html",
    "https://www.bulkreefsupply.com/aquarium-lighting/wholesale-lighting-highlights.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/aquarium-silicone.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/aquarium-silicone.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/diy-screen-tops.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/diy-screen-tops.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/ato-reservoirs.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/ato-reservoirs.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/scratch-removers.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/scratch-removers.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/refugiums.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/refugiums.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/overflows/external.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/overflows/internal.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/overflows.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/overflows.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/aquaforest.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/fiji-cube.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/eshopps.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/reef-octopus.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/icecap.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/trigger-systems.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps/hmahli.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/sumps.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-by-brand.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/all-in-one-aio-aquariums.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/reef-ready-aquariums.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-over-201-gallons.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-151-to-200-gallons.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-101-150-gallons.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-51-100-gallons.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks/aquariums-under-50-gallons.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/tanks.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/wholesale-highlights/trigger-systems.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/wholesale-highlights/cpr-aquatics.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/wholesale-highlights/screen-tops.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/sumps-tanks-refugiums/wholesale-highlights.html",
    "https://www.bulkreefsupply.com/brs-wholesale/specials.html",
    "https://www.bulkreefsupply.com/brs-wholesale/best-margin-brands.html",
]
